### ISSUE TITLE
Input tsv file requires absolute paths to reads

### ISSUE THREAD

**Issue by pansapiens** [kristyhoran/bohra#2]
**Expected behaviour:**

Given a `-i` TSV input file with relative paths to FASTQ files, eg:
```
sample1   DRR033844_1.fastq.gz    DRR033844_2.fastq.gz
sample2   DRR033845_1.fastq.gz    DRR033845_2.fastq.gz
sample3   DRR033846_1.fastq.gz    DRR033846_2.fastq.gz
sample4   DRR033847_1.fastq.gz    DRR033847_2.fastq.gz
```

`bohra` should run succesfully, creating the correct symlinks in `READS/{isolate}/`.

**Observed behaviour:**

`bohra` treats the filenames in the `-i` TSV file as absolute paths, such that in the example above symlinks in `READS/{isolate}/` will be broken. For generating the links in `READS`, `bohra` should do one of:

1. create _relative_ links from `READS/{isolate/` to the location of the read files.
2. convert relative paths in the TSV file to absolute paths based on the current working directory of invocation
3. fail if paths in TSV file are not absolute or files don't exist (eg, must start with `/`, check `os.path.exists(f) and os.path.isfile(f)` )

To replicate:

Setup a test dataset:
```sh
wget ftp://ftp.ensemblgenomes.org/pub/bacteria/release-44/fasta/bacteria_5_collection/enterococcus_faecium_505/dna/Enterococcus_faecium_505.ASM29533v2.dna_sm.toplevel.fa.gz

for r in {1..2}; do for i in {4..7}; do wget -c ftp://ftp.sra.ebi.ac.uk/vol1/fastq/DRR033/DRR03384${i}/DRR03384${i}_${r}.fastq.gz; done; done

# Create a tsv input file
echo -e "sample1\tDRR033844_1.fastq.gz\tDRR033844_2.fastq.gz\nsample2\tDRR033845_1.fastq.gz\tDRR033845_2.fastq.gz\nsample3\tDRR033846_1.fastq.gz\tDRR033846_2.fastq.gz\nsample4\tDRR033847_1.fastq.gz\tDRR033847_2.fastq.gz" >efac.tsv
```

Run `bohra`, fails with the error:
```sh
$ bohra run -r Enterococcus_faecium_505.ASM29533v2.dna_sm.toplevel.fa.gz -i efac.tsv -j fqpathtest
Building DAG of jobs...
MissingInputException in line 52 of /scratch/df22/andrewpe/bohra/testrun/Snakefile:
Missing input files for rule seqdata:
READS/sample4/R2.fq.gz
READS/sample4/R1.fq.gz
```

`bohra` version is 1.0.3 (from this repo, latest commit https://github.com/kristyhoran/bohra/commit/c935e9971d07496eab4040dd4069c57be7075a70)

**Comment by kristyhoran** [comment]
@pansapiens Thanks for that. I had not thought of that! I think a combination of 2 and 3 would address the issue. I'll let you know how it goes. Cheers
Kristy

**Comment by kristyhoran** [comment]
@pansapiens I implemented suggestions 2 and 3, first if not an absolute path convert and then check that it did in fact exist. Raise an error informing user and suggesting they look at input file. Thanks for the suggestion!
